language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할 지 지정
# 현재는 master 에 push 될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여
# 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# permission denied
before_install:
  - chmod +x gradlew # install 전 미리 실행 권한 추가

before_deploy:
  - chmod +x gradlew
  - zip -r com.test.aws
  - mkdir -p deploy # deploy 디렉토리를 Travis CI 가 실행중인 위치에서 생성
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: freelec-springboot-build-prac #s3 burket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dudekekek@gmail.com


